### ISSUE TITLE
Acentos, Mayusculas, y Ortografia

### ISSUE THREAD

**Issue by diegomartin010** [diegomartin010/100tifiko#13]
Cristina odia los errores ortograficos.

Verificar en todo el sistema:

- Que los acentos esten bien puestos.

- Que todas las acciones, titulos, palabras, etc, empiecen con mayuscula.

- Si un boton, por ejemplo dice ** "cargar evento"**, modificar por **"Cargar Evento"** (las palabras "de" "en" "un" "mi" "el", etc.... no se van a poner con mayuscula. Solo los sustantivos.)

**Comment by martindegesus** [comment]
En el módulo de estadísticas, la unidad del tiempo de carrera es "Anios" , poner ñ

**Comment by martindegesus** [comment]
Verifiqué todos los GSP, capaz se me pasó algo.

Algunas cosas las pasé de inglés a español para ser consistentes con el idioma, ej:

Username -> Nombre de usuario
Password -> Contraseña

Cosas como logín o logout los dejé así.

Atentos a que coincidan con la ERS

Si encuentran otro error ponganlo acá o arreglenlo
