### ISSUE TITLE
Index -> DropDown Alarmas

### ISSUE THREAD

**Issue by diegomartin010** [diegomartin010/100tifiko#16]
**Relacionado con Issue #5** 
Terminar de darle la funcionalidad al dropdown.

Deben mostrarse todas las notificaciones de 15 dias o menos.

![captura](https://cloud.githubusercontent.com/assets/9575268/20376417/3f588570-ac65-11e6-8d3e-e405643fa7ab.PNG)

**Comment by martindegesus** [comment]
Actualmente el dropdown de alarmas, muestra eventos pasados, lo cual no es adecuado.
