### ISSUE TITLE
Fechas en la Agenda

### ISSUE THREAD

**Issue by diegomartin010** [diegomartin010/100tifiko#24]
Basicamente no se bien como hacer el tratamiento de las fechas. No se si es un tema de mi PC, y capaz en las de ustedes ande.... pero a mi me guarda mal las fechas.

**Comment by martindegesus** [comment]
eso te pasa
por no respetar
el formato de parsing.

**Comment by martindegesus** [comment]
Algo a corregir: La agenda deja anotar eventos con fechas previas a la actual.

**Comment by martindegesus** [comment]
Solucionado
