### ISSUE TITLE
Pantalla de tutorial

### ISSUE THREAD

**Issue by martindegesus** [diegomartin010/100tifiko#26]
El sistema necesita una pequeña guia de como vincularse a una carrera, agregar examenes, etc.

Para cualquier usuario que no esté familiarizado con el sistema, el sistema es dificil de comprender.

Propongo, cambiar la pantalla actual de "home" por una pantalla en la que haya una pequeña guia.

O dejar la página actual como está y hacer un "get started".

**Comment by martingaleano** [comment]
basicamente si.
