### ISSUE TITLE
Imagen inicial carousel

### ISSUE THREAD

**Issue by martindegesus** [diegomartin010/100tifiko#29]
La imagen inicial del carousel, no es la que dice "bienvenidos", debería serlo.

**Comment by martindegesus** [comment]
Básicamente estan bastantes desordenados a mi criterio.

propongo:

1- "bienvenidos"
2- "como empezar"
3- a criterio suyo

**Comment by diegomartin010** [comment]
Mira..... Grails basicamente muestra las imagenes acorde a como el sistema de archivos le proporcione los nombres..... no se en que orden mostrara en tu pc con linux ... no entiendo muy bien como funciona esta caracteristica de grails.

**Comment by martindegesus** [comment]
Resuelto por diego
