### ISSUE TITLE
FALTA LA CONTRASEÑAAAAAAAAAAAAAAA

### ISSUE THREAD

**Issue by martindegesus** [diegomartin010/100tifiko#41]
El administrador puede crear usuarios pero no asignarles una contraseña.

Pongo en la documentación que se le asigna la contraseña. 

Si no lo quieren codificar borrenlo de la ERS (U-2.1)

**Comment by martindegesus** [comment]
nota: incluí repetir contraseña

**Comment by diegomartin010** [comment]
El administrador NO PUEDE crear contraseña. 

Básicamente si un admin te crea un usuario, te llega a tu mail el username que seteo el administrador, y te llega una contraseña random.

Ahora esta seteado para que cuando el usuario se crea, te pongan la misma contraseña qeu el username.
